-- Author : Samuel de Lima Lopes
-- Data: 16/02/2018
-- Versão 1.0.0

CREATE DATABASE TESTE;
USE TESTE;

CREATE TABLE TB_CUSTOMER (
	ID_CUSTOMER INTEGER NOT NULL,
    NM_CUSTOMER VARCHAR(25) NOT NULL,
    CPF_CNPJ NUMERIC(14, 0) NOT NULL
);

ALTER TABLE TB_CUSTOMER MODIFY ID_CUSTOMER INTEGER AUTO_INCREMENT PRIMARY KEY;

CREATE TABLE DM_ADDRESS_TYPE (
	CD_ADDRESS_TYPE CHAR(1) NOT NULL,
    DS_ADDRESS_TYPE VARCHAR(40) NOT NULL
);

ALTER TABLE DM_ADDRESS_TYPE ADD PRIMARY KEY(CD_ADDRESS_TYPE);

CREATE TABLE TB_CUSTOMER_ADDRESS (
	ID_CUSTOMER INTEGER NOT NULL,
    CD_ADDRESS_TYPE CHAR(1) NOT NULL,
    STREET VARCHAR(40) NOT NULL,
    LOT INTEGER NOT NULL,
    `REFERENCES` VARCHAR(40) NOT NULL,
    ZIP_CODE VARCHAR(30) NOT NULL
);

ALTER TABLE TB_CUSTOMER_ADDRESS ADD PRIMARY KEY(ID_CUSTOMER, CD_ADDRESS_TYPE);
ALTER TABLE TB_CUSTOMER_ADDRESS ADD CONSTRAINT FK_TB_CUSTOMER_ID_CUSTOMER FOREIGN KEY(ID_CUSTOMER) REFERENCES TB_CUSTOMER(ID_CUSTOMER);
ALTER TABLE TB_CUSTOMER_ADDRESS ADD CONSTRAINT FK_TB_CUSTOMERCD_ADDRESS_TYPE FOREIGN KEY(CD_ADDRESS_TYPE) REFERENCES DM_ADDRESS_TYPE(CD_ADDRESS_TYPE);

-- PREENCHENDO TABELAS
INSERT INTO DM_ADDRESS_TYPE (CD_ADDRESS_TYPE, DS_ADDRESS_TYPE) VALUES ('R', 'Residêncial');
INSERT INTO DM_ADDRESS_TYPE (CD_ADDRESS_TYPE, DS_ADDRESS_TYPE) VALUES ('C', 'Comercial');
INSERT INTO DM_ADDRESS_TYPE (CD_ADDRESS_TYPE, DS_ADDRESS_TYPE) VALUES ('O', 'Outros');

INSERT INTO TB_CUSTOMER (NM_CUSTOMER, CPF_CNPJ) VALUES ('Joãozinho Silva', 88877766655);

INSERT INTO TB_CUSTOMER_ADDRESS(ID_CUSTOMER, CD_ADDRESS_TYPE, STREET, LOT, `REFERENCES`, ZIP_CODE) VALUES
							   (1, 'R', 'Rua das Flores', 1, '', '01234-567');
                               
INSERT INTO TB_CUSTOMER_ADDRESS(ID_CUSTOMER, CD_ADDRESS_TYPE, STREET, LOT, `REFERENCES`, ZIP_CODE) VALUES
							   (1, 'C', 'Rua das Pedras', 100, 'Conjunto 200', '01234-567');                         